name: Deployment - API
env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
on:
  push:
    branches:
      - master
    paths:
      - apps/api/**
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: 🔦 Run linter
        run: bun run lint
        working-directory: ./apps/api
      - name: 🪐 Check TypeScript
        run: bun run typecheck
        working-directory: ./apps/api
      - name: 🧪 Run unit tests
        run: bun test
        working-directory: ./apps/api
      - name: Deploy Project Artifacts to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: bun
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "apps/api"
          command: deploy --minify src/server.ts